// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGv1e4WOOMkmKUpekWOunvxvOWJujEaFU',
    appId: '1:300283951356:web:9dfbc77d765c20fdb77f79',
    messagingSenderId: '300283951356',
    projectId: 'inclass13-mad1717',
    authDomain: 'inclass13-mad1717.firebaseapp.com',
    storageBucket: 'inclass13-mad1717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6FdqgEGnh0j6rsg0m-NY1E7aH1ZT_Cg',
    appId: '1:300283951356:android:5280a6c0ba3512c1b77f79',
    messagingSenderId: '300283951356',
    projectId: 'inclass13-mad1717',
    storageBucket: 'inclass13-mad1717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpdbx16T_pa_slixinGw-LlY_eZH0noEY',
    appId: '1:300283951356:ios:66ca0ee684244da4b77f79',
    messagingSenderId: '300283951356',
    projectId: 'inclass13-mad1717',
    storageBucket: 'inclass13-mad1717.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpdbx16T_pa_slixinGw-LlY_eZH0noEY',
    appId: '1:300283951356:ios:66ca0ee684244da4b77f79',
    messagingSenderId: '300283951356',
    projectId: 'inclass13-mad1717',
    storageBucket: 'inclass13-mad1717.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );
}
